### ISSUE TITLE
multiprocessing error?

### ISSUE THREAD

**Issue by kassasin** [LeCAR-Lab/dial-mpc#2]
Amazing job !!! I got an error when I run "dial-mpc-plan --example unitree_go2_seq_jump_deploy":
```
jaxlib.xla_extension.XlaRuntimeError: FAILED_PRECONDITION: cuSolver has not been initialized
/root/miniforge3/lib/python3.10/multiprocessing/resource_tracker.py:224: UserWarning: resource_tracker: There appear to be 6 leaked shared_memory objects to clean up at shutdown
  warnings.warn('resource_tracker: There appear to be %d 
```

**Comment by kassasin** [comment]
The reason is I used too much gpu ?

**Comment by simeon-ned** [comment]
I've encountered the same issue. It appears that after running the command:

```bash
dial-mpc-sim --example unitree_go2_seq_jump_deploy
```

a significant amount of memory is occupied on the GPU (nvidia-smi reports 6 GB of VRAM usage). Is this amount of memory intended? This is unexpected, as I understood this should just be a MuJoCo simulation running in parallel. Consequently, there isn't enough memory available for:

```bash
dial-mpc-plan --example unitree_go2_seq_jump_deploy
```

Could you let me know if there are any recommended solutions or workarounds for this?

By the way, thank you for this excellent library! I'm eager to contribute some examples if that's alright with you.

**Comment by jc-bao** [comment]
Thanks for your interest in our project!

1. Why am I getting an "out of resource" error?

DIAL-MPC needs to be run on a GPU, and the error cuSolver has not been initialized suggests that your GPU is not properly initialized due to a CUDA issue. Please check your JAX installation and ensure that the CUDA-enabled version of JAX is set up correctly.

2. Why is so much memory being used?

JAX preallocates GPU memory to optimize computational speed. You can read more about this feature here: [JAX GPU Memory Allocation](https://jax.readthedocs.io/en/latest/gpu_memory_allocation.html).

Let me know if you need further assistance!

**Comment by kassasin** [comment]
@jc-bao I am using nvidia 4090 to run these program, before this error happened, almost all gpu(24g) has been used.

**Comment by jc-bao** [comment]
@kassasin If that's the case, make sure you have a entire GPU for DIAL-MPC. As a online algorithm, it need a whole GPU to make it perform the best.

**Comment by kassasin** [comment]
@jc-bao how much should I prepare for it? Because I have only 24g (4090) and there are no other program use gpu .
```
dial-mpc-sim --example unitree_go2_seq_jump_deploy
dial-mpc-plan --example unitree_go2_seq_jump_deploy
```

**Comment by jc-bao** [comment]
oh i see. a single 4090 should be more than enough. Just make sure you don't have other programs that consumes the computation power of the GPU.

**Comment by kassasin** [comment]
I just taken another try .
After i run first command:
`dial-mpc-sim --example unitree_go2_seq_jump_deploy`
19g gpu occupied.
After i run second command:
`dial-mpc-plan --example unitree_go2_seq_jump_deploy`
almost all gpu occupied. and error happend soon .
Is this normal?

**Comment by kassasin** [comment]
I also noticed some warning:
`The NVIDIA driver's CUDA version is 12.0 which is older than the PTX compiler version 12.6.68. Because the driver is older than the PTX compiler version, XLA is disabling parallel compilation, which may slow down compilation. You should update your NVIDIA driver or use the NVIDIA-provided CUDA forward compatibility packages.`
Is this a problem?

**Comment by kassasin** [comment]
More infomation:
I just 
`export XLA_PYTHON_CLIENT_PREALLOCATE=false` to all terminal .
It only use 2g gpu. All things are normal except "[WRAN] real overtime 24.0 ms"

**Comment by kassasin** [comment]
`export XLA_PYTHON_CLIENT_MEM_FRACTION=0.5`
This command can also solve this problem on 4090 but also have overtime problem .

**Comment by HaoruXue** [comment]
Thanks for reporting the issue! We just updated the code to fix a memory issue on the simulation code

@kassasin could you pull the latest code and try again?

**Comment by kassasin** [comment]
Thank you very much, I just take a test. It is perfect !!!

**Comment by kassasin** [comment]
By the way, overtime problem still have, Is this normal?

**Comment by HaoruXue** [comment]
> By the way, overtime problem still have, Is this normal?

Yeah it happens. For the stability of the examples we tuned up some horizon and sample settings to make the examples more stable. Feel free to change the settings a little in the example folder.

When overtime happens, DIAL-MPC will continue to execute action from the solution buffer. We don't see a significant downgrade in performance, but certainlly we are working on more optimized settings to prevent overtime from happening.
