### ISSUE TITLE
jax 0.4.13 does not provide the extra 'cuda12

### ISSUE THREAD

**Issue by lyc-1996** [LeCAR-Lab/dial-mpc#5]
error "jax 0.4.13 does not provide the extra 'cuda12'" occurred when I tried "dial-mpc --list-examples" or "dial-mpc --example unitree_h1_jog".
Should i change the version of jax?

**Comment by jc-bao** [comment]
What platform are you using? You might find [this issue](https://github.com/jax-ml/jax/issues/17634#issuecomment-1722517540) helpful!

**Comment by lyc-1996** [comment]
My platform is ubuntu20.04.
now I have changed Cuda12.6+cudnn8.8+jax0.4.7
but still get the error "pkg_resources.UnknownExtra: jax 0.4.7 has no such extra feature 'cuda12' " when I tried "dial-mpc --list-examples"

**Comment by HaoruXue** [comment]
Hmm we can try reproducing this on Ubuntu 20.04.

Your cudnn and jax version does seem a bit outdated. What python version are you using?

Meanwhile if possible can you try a conda environment which a recent python version (>= 3.10) and jax version (we have 0.4.33)?

Feel like this is more of a python install issue.

**Comment by lyc-1996** [comment]
thanks for your reply
after changing my python3 version from 3.8 to 3.10, the origin problem has been solved .
I believe there's something wrong with the ubuntu20.04+python3.8.
By the way, it's hard to change the python3 version for me because i am not familiar with it. MANY MANY MANY issues happened !! So i strongly advice that other coders should follow the recommended environment !!!

**Comment by HaoruXue** [comment]
Thanks for the update!
