### ISSUE TITLE
unitree_H1 simulation deployment failed

### ISSUE THREAD

**Issue by YHFone** [LeCAR-Lab/dial-mpc#6]
hi! 
I want to deploy the H1 example in mujoco, just like GO2, added the relevant deploy.yaml, and then added "unitree_h1_jog_deploy" in deploy_examples. When running asynchronous simulation, the effect is particularly poor, the trajectory planned by H1 is all messy, and adjusting the relevant rewards and joints KP, KD does not improve significantly.
![dial-mpc-sim](https://github.com/user-attachments/assets/e1592f97-7ab7-4473-be09-1b05d427cca5)
![dial_mpc_plan](https://github.com/user-attachments/assets/846186e2-d5a6-4f97-be5a-e04df63ba529)
![2024-10-21 11-40-26屏幕截图](https://github.com/user-attachments/assets/f4cd8337-2e66-436e-9aa5-e741fe201640)

**Comment by HaoruXue** [comment]
Yes we are working on H1 deployment 😉 stay tuned
