### ISSUE TITLE
Asynchronous simulation encounters multi process issues

### ISSUE THREAD

**Issue by rl180** [LeCAR-Lab/dial-mpc#8]
resource_tracker.py:224: UserWarning: resource_tracker: There appear to be 6 leaked shared_memory objects to clean up at shutdown
  warnings.warn('resource_tracker: There appear to be %d '
How to solve the problem with the terminal prompt

**Comment by HaoruXue** [comment]
Currently this issue won't affect the successful running of DIAL-MPC, but I agree it would be a proper practice to resolve this.

This is basically due to the `SharedMemory` instances in `dial-mpc-plan` and `dial-mpc-sim` not properly released. We welcome PRs to fix this one!
